ALBUM_IDS                       = ""
IMAGE_SIZE_TYPE                 = "z" # https://dev.vk.com/reference/objects/photo-sizes#type
LOGIN_DATA_PATH                 = "../LoginData/login.json"
FACIAL_POINTS_MODEL             = "large" # small/large - faster,lower accuracy/slower,higher accuracy
FACE_BOXES_MODEL                = "cnn" # hog/cnn - faster,lower accuracy/slower,higher accuracy
NUMBER_OF_ATTEMPTS              = 3 # number of attempts in case of connection error
NUM_JITTERS                     = 4 # higher the value - slower the execution
OLDEST_ALBUM_UNIX_TIME          = -1
OWNER_ID                        = ""
LIST_PHOTOS_PICKLE_FILENAME     = "list_photos.pickle"
RESTORE_PHOTO_URLS_FROM_PICKLE  = False
IMG_URLS_OFFSET                 = 0
SUPPRESS_NOT_FOUND_IN_ALBUMS    = True
TOLERANCE                       = 0.5 # lower - better